# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "無料で使えるシステムトレードフレームワーク「Jiji」"
email: masaya.yamauchi@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  自分だけの取引アルゴリズムで、今すぐシステムトレードを開始。
  「Jiji」は、無料で使えるFXシステムトレードフレームワークです。
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jiji2.unageanu.net" # the base hostname & protocol for your site

exclude: [vendor]

# Build settings
markdown: kramdown

port: 8000
host: 0.0.0.0

collections:
 install:
    output: true
 usage:
    output: true
