
default:
  clients:
    default:
      hosts: &hosts
        - 127.0.0.1:27017
  options: &options
    raise_not_found_error: false

production:
  clients:
    default:
      database: jiji
      hosts:   *hosts
  options: *options

development:
  clients:
    default:
      database: jiji_dev
      hosts:   *hosts
  options: *options

test:
  clients:
    default:
      database: jiji_test
      hosts:   *hosts
  options: *options
